### ISSUE TITLE
package.json is not working properly for window 7 when npm run.

### ISSUE THREAD

**Issue by sheryltohxn** [singpath/classmentors#134] opened 2016-10-11 12:47 UTC
The current package.json is not working for window 7. When npm install, several critical files are missing that are required for npm start. After inspecting the codes, it was found that the missing ".js" is the cause of the problem. In order for it to work for windows, the codes need to be changed to include ".js". Below is a snippet from the package.json:
From
`github:ajaxorg/ace-builds@1.2.5": {
        "main": "ace",
        "format": "global",
        "directories": {
          "lib": "src-noconflict"
        },`
To 
`github:ajaxorg/ace-builds@1.2.5": {
        "main": "ace.js",
        "format": "global",
        "directories": {
          "lib": "src-noconflict"
        },`

Another issue I wish to highlight was the discrepancy in the package versions. For example, the firebase-bower version declared under peer dependencies is 3.3.0.(line 82) But the dependency version for angularfire was 3.0.0(line 237) and a version 3.3.2 firebase-bower(line 249) is installed. I am not sure if this is a typo error.

**Comment by shiquan-lim** [comment] 2016-10-11 13:49
@dinoboff To elaborate, this error was introduced in commit fb5042c2cf89e42b874f29ef6ba1d6135704319d on Sept 11. Running npm install on an already functioning local project will not affect anything - but you will notice that fresh clones fail due to errors in the package.json file.

**Comment by dinoboff** [comment] 2016-10-13 21:58
@shiquan-lim Unfortunately in fb5042c, there's an issue with package.json (It couldn't be merged with on earlier merge where everything had changed) so I don't know what changed in package.json.

is it windows specific? on mac, after removing node_modules/ and src/jspm_packages/, and reinstalling it still works.

And what's the error? Does it happen during "npm install" and or when the page load? Which files are missing?

@sheryltohxn setting the extension on the main property doesn't seem to have a side effect.

As for firebase version, angularFire should work with any 3.x.x version. Class Mentors require 3.3.0 higher. Those versions definition should be compatible. Did jspm complain?

**Comment by dinoboff** [comment] 2016-10-14 10:53
I tried on Win 10 with a fresh clone: "npm install" works and the page load (ace files get downloaded). I unfortunately can't currently test on Win 7 (performance and network issue from my virtual machines).

Can you please give more details about the error?

**Comment by sheryltohxn** [comment] 2016-10-15 15:40
Hi @dinoboff.  jspm didn't complain about the versions. as for the package.json, when i do a fresh clone of the project and do "npm install" "npm build" then start, the main page didnt load and the errors are about certain .js files missing. E.g. in jspm_packages/github/firebase/firebase-bower@3.3.2 , firebase.js was missing even "npm install" is done.

**Comment by dinoboff** [comment] 2016-10-16 08:52
Do you mean `src/jspm_packages/github/firebase/firebase-bowe@3.3.2/firebase.js` doesn't exist or that it exists but the page fails to load it?

If the file doesn't exist, there's might have been an issue while downloading it. Try, using a fresh clone from https://github.com/singpath/classmentors (and using bash that comes with "git for windows"):

```
jspm cache-clear
rm -rf src/jspm_packages
jspm install
```

Please paste the output from the console.

If the js files exists but the systemjs fails to load them on win7 when some `main` properties use implicit file extension, try to upgrade jspm:

```
npm install jspm@beta
```

If it still fails I will try to reproduce and isolate the bug later when I have to have access to windows 7, and submit it to jspm.

**Closed as completed** 2016-11-25 00:58 UTC
